version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    level: NOTSET

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: '/var/log/energyapp/daily_usage.log'
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  daily_usage:
    level: DEBUG
    handlers: [file]
    propagate: no

  database_operations:
    level: INFO
    handlers: [file]
    propagate: no

root:
  level: WARNING
  handlers: [file]
