version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: '/var/log/energyapp/daily_usage.log'
    maxBytes: 5*1024*1024  # 5MB
    backupCount: 5           # Keep 5 backup files

loggers:
  daily_usage_logger:
    level: INFO
    handlers: [console, rotating_file]
    propagate: no

root:
  level: WARNING
  handlers: [console]
